# Generated by Django 3.1.6 on 2021-02-04 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
