# Generated by Django 3.1.2 on 2021-02-16 09:56

import datetime
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test', max_length=100, unique=True)),
                ('description', models.CharField(default='Test', max_length=1000)),
                ('priority', models.CharField(default='Delete', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', max_length=100)),
                ('description', models.CharField(default='Test', max_length=1000)),
                ('priority', models.CharField(max_length=100)),
                ('project', models.CharField(blank=True, max_length=100)),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('critical_path', models.BooleanField(default='False')),
                ('time_required', models.DurationField(default=datetime.timedelta(seconds=3600))),
            ],
        ),
    ]
