# Generated by Django 3.1.6 on 2021-02-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='userid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
