# Generated by Django 3.1.6 on 2021-02-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_tasks_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='text',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
