# Generated by Django 3.1.2 on 2021-02-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_auto_20210216_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='project_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='papp.projects'),
            preserve_default=False,
        ),
    ]
