# Generated by Django 3.1.6 on 2021-02-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0003_auto_20210209_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.CharField(default='yyyyMMddHHmmssfff', max_length=100, primary_key=True, serialize=False),
        ),
    ]
