# Generated by Django 3.1.6 on 2021-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0004_auto_20210216_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.CharField(blank=True, choices=[('No Project', 'No Project'), ('First', 'First'), ('Test', 'Test')], default='*', max_length=100),
        ),
    ]
