# Generated by Django 3.1.6 on 2021-02-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0005_auto_20210210_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(default='Delete', max_length=20),
        ),
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='text',
            field=models.CharField(default='Test', max_length=500),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='userid',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
