# Generated by Django 3.1.6 on 2021-02-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0005_auto_20210216_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
    ]
