# Generated by Django 3.1.6 on 2021-02-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0006_remove_tasks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.CharField(blank=True, default='*', max_length=100),
        ),
    ]
