# Generated by Django 3.1.6 on 2021-02-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0008_auto_20210216_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('JDI', 'JDI'), ('UI', 'UI'), ('U', 'U'), ('I', 'I'), ('D', 'D')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.CharField(blank=True, choices=[(' ', ' '), ('No Project', 'No Project'), ('Third', 'Third'), ('First', 'First'), ('Second', 'Second'), ('Test', 'Test'), ('4', '4')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
