# Generated by Django 3.1.6 on 2021-02-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0009_auto_20210216_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='project_id',
        ),
    ]
