# Generated by Django 3.1.6 on 2021-02-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0010_remove_tasks_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
