# Generated by Django 3.1.6 on 2021-02-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0011_tasks_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='priority',
            field=models.CharField(choices=[('JDI', 'JDI'), ('UI', 'UI'), ('U', 'U'), ('I', 'I'), ('D', 'D')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.CharField(blank=True, choices=[(' ', ' '), ('Project', 'Project')], default=' ', max_length=100),
        ),
    ]
