# Generated by Django 3.1.6 on 2021-02-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0012_auto_20210217_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.CharField(default='Old user', max_length=50),
            preserve_default=False,
        ),
    ]
